### ISSUE TITLE
gatsby compile html.js error

### ISSUE THREAD

**Issue by Void-light** [njosefbeck/gatsby-plugin-stripe-elements#3]
initially it was fine while at localhost:8000 but now there is an error 
gatsby develop
`gatsby develop
success delete html and css files from previous builds — 0.024 s
success open and validate gatsby-config — 0.005 s
success copy gatsby files — 0.013 s
success onPreBootstrap — 0.010 s
success source and transform nodes — 0.015 s
success building schema — 0.100 s
success createLayouts — 0.019 s
success createPages — 0.001 s
success createPagesStatefully — 0.017 s
success onPreExtractQueries — 0.001 s
success update schema — 0.062 s
success extract queries from components — 0.073 s
success run graphql queries — 0.030 s
success write out page data — 0.009 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 2.382 s

error There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  Error: Module build failed: Error: Plugin/Preset files are not allowed to expo  rt objects, only functions. In /home/bk/gatsby-site/node_modules/babel-preset-  stage-0/lib/index.js
  
  - config-descriptors.js:178 createDescriptor
    [gatsby-site]/[@babel]/core/lib/config/config-descriptors.js:178:11
  
  - config-descriptors.js:109 items.map
    [gatsby-site]/[@babel]/core/lib/config/config-descriptors.js:

`

Index of 
public/

    static/

`"use strict";

exports.__esModule = true;

var _babelPresetStage = require("babel-preset-stage-1");

var _babelPresetStage2 = _interopRequireDefault(_babelPresetStage);

var _babelPluginTransformDoExpressions = require("babel-plugin-transform-do-expressions");

var _babelPluginTransformDoExpressions2 = _interopRequireDefault(_babelPluginTransformDoExpressions);

var _babelPluginTransformFunctionBind = require("babel-plugin-transform-function-bind");

var _babelPluginTransformFunctionBind2 = _interopRequireDefault(_babelPluginTransformFunctionBind);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

exports.default = {
  presets: [_babelPresetStage2.default],
  plugins: [_babelPluginTransformDoExpressions2.default, _babelPluginTransformFunctionBind2.default]
};
module.exports = exports["default"];`
`

**Comment by njosefbeck** [comment]
@Void-light Hello! So I just double checked in a gatsby test site that I have, and there were no errors when running `gatsby develop` or `gatsby build`. The stripe script was also loaded on each page properly. My test site is using Gatsby version 1.9.277 and version 1.0.8 of this plugin.

To try to help you debug further:

- What version of Gatsby are you running?
- Are you using [React Stripe Elements](https://github.com/stripe/react-stripe-elements) to load your elements?
- Do you have any code in a repo that I could look at to help you debug?
- If not, are you using any other Gatsby plugins which could be causing this error? I ask this, because my plugin is simple, and does export a function, thus satisfying the error: `Error: Plugin/Preset files are not allowed to export objects, only functions.`

Happy to help you debug further! Thanks for reaching out!

**Comment by Void-light** [comment]
@njosefbeck
Hi ! I deleted the gatsby site and again created and developed and works
fine. However, if I tried to install  babel new version as suggested
everything goes wrong.
Message as follows:
"Thanks for using Babel: we recommend using babel-preset-env now: please
read babeljs.io/env to update!"

**Comment by njosefbeck** [comment]
As this doesn't seem to have to do with an issue with my plugin, I'm going to close this issue for now. Feel free to open again if needed! Thanks!
